### ISSUE TITLE
bug(s) when filling dates for `B` to match simulation horizon

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/reem#20]
@davidchampredon, i've noticed one definite issue and one potential bug in the date filling functionality of `check_B()`.

**(possible bug)** 
[simulate.R#276](https://github.com/phac-nml-phrsd/reem/blob/57f498447a8af0ef8a3a58f3edbe39e75d866c53/R/simulate.R#L276) 
`date.horiz = obj$prms$date.start + obj$prms$horizon`

here, the simulation end date is being calculated as the start date + the horizon. should this not be start date _- start delta_ + horizon? that's how i understood start delta to be used. am i wrong?

**(definite bug)**
[simulate.R#293](https://github.com/phac-nml-phrsd/reem/blob/57f498447a8af0ef8a3a58f3edbe39e75d866c53/R/simulate.R#L293C2-L293C30): 
```
if(obj$prms[['B']]$date[nb] < date.horiz){
```

this check occurs with the number of rows of `B`, `nb`, computed **before** the fill towards the start dates gets complete (if it does). `nb` should be recomputed, as on [line 300](https://github.com/phac-nml-phrsd/reem/blob/57f498447a8af0ef8a3a58f3edbe39e75d866c53/R/simulate.R#L300) before line 293. otherwise, the warning message reports a last `B` date that is too early and will trigger even when the last `B` date is exactly the simulation end date (if there is any filling toward the start date). this then causes an error in [line 303](https://github.com/phac-nml-phrsd/reem/blob/57f498447a8af0ef8a3a58f3edbe39e75d866c53/R/simulate.R#L303) when there is an attempt to compute `d2 = seq.Date(obj$prms[["B"]]$date[nb] + 1, date.horiz, by = 1)` (the first date will be after the second date so R will report that the sign of the `by` argument is wrong)

i can fix the second one myself and create a pull request, but i hesitate to fix the first one without clarifying with you whether it was intended or not.

**Comment by davidchampredon** [comment]
Regarding the "possible bug", the variable `start.delta` is used only when fitting (function `reem_traj_dist_obs()` in `fit.R`). The variable `start.delta` is used to update `start.date` and `horizon` before the simulation is run (within the fitting process). 
The function `check_B()` checks for `B` at the simulation step only (in `reem_simulate_epi ()`), so it is correct to ignore `start.delta` in the check. However, it should be more obvious that `start.delta` is used only during the fit. If the user wants to change the start date of the simulation, they should update `prms$start.date` directly. I will make that clear (new issue #21, thanks for pointing this out. 

"definite bug": yes indeed a bug. Thanks! Fixed!

**Comment by papsti** [comment]
that makes sense about the `start.delta`, but what happens to `B` in fit simulations when `start.delta` is non-zero in the fit? is there another step where `B[1]` is filled to the new start date of `date.start` - `start.delta` and `B[n]` is filled to the new end date (if need be)? or is `simulate_epi` being called here too, so it's using the same code for filling in the fit sims?

**Comment by davidchampredon** [comment]
> what happens to B in fit simulations when start.delta is non-zero in the fit?

`simulate_epi` is called inside `reem_traj_dist_obs()`, hence `check_B()` is called too, so `B` will be extrapolated.

> is there another step where B[1] is filled to the new start date of date.start - start.delta and B[n] is filled to the new end date (if need be)? or is simulate_epi being called here too, so it's using the same code for filling in the fit sims?

Only `check_B()` overwrites `B` and this happens only when `simulate_epi()` is called. So, that _should_ be airtight...

**Comment by papsti** [comment]
i can confirm that after updating to the latest version of `reem`, this issue is resolved!

just a note for myself, i documented my work understanding these bugs in `reemscenex` [bdbb014](bdbb0140be79d382af5ab9d2ca9be419c5332a67)
